version: '3'
services:

  camunda:
    image: coopersoft/hsr-camunda:1.0-SNAPSHOT
    ports:
      - "19005:19005"
    environment:
      PROFILE: "default"
      SERVER_PORT: "19005"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: consul
      DB_URL: "jdbc:mariadb://192.168.1.21:3306/camunda?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowMultiQueries=true"
      DB_USERNAME: "root"
      DB_PWD: "5257mq"
      JWT_ISS: https://192.168.1.21:8443/realms/house-sale
      MQ_ADDR: 192.168.1.21:9876
      TZ: Asia/Shanghai

