logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    cc.coopersoft: DEBUG

server:
  port: 8080
  servlet.context-path: /camunda

management:
  health.probes.enabled: true
  endpoints:
    web.exposure.include: env,health,info,metrics

camunda.bpm:
  eventing:
    execution: true
    task: true
    history: false
    skippable: true
  historyLevel: audit
  database:
    schema-update: drop-create
    type: mariadb
#  webapp:
#    index-redirect-enabled: true
  authorization:
    enabled: false
  run:
    cors:
      enabled: true
      allowed-origins: "*"
  filter:
    create: All tasks
  webapp.application-path:

keycloak:
  url.auth: ${KEYCLOAK_URL_AUTH:https://192.168.1.21:8443}
  url.token: ${KEYCLOAK_URL_TOKEN:https://192.168.1.21:8443}
  url.plugin: ${KEYCLOAK_URL_TOKEN:https://192.168.1.21:8443}
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET:7Osuidv7klOGg80FruUrm6bDFvg4SnQr}

plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/realms/house-sale
  keycloakAdminUrl: ${keycloak.url.plugin}/admin/realms/house-sale
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true

rest.security:
  enabled: true
  provider: keycloak
  required-audience: camunda-rest-api

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
    consul:
      ribbon:
        enabled: false
      config:
        enabled: true
        format: yaml
        prefixes: config
        profile-separator: ':'
        data-key: data
      discovery:
        serviceName: ${spring.application.name}
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true

        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    function:
      definition: processCreateChannel
    stream:
      bindings:
        processCreateChannel-in-0:
          #RocketMQ Topic
          destination: topic-process-create
          content-type: application/json
          group: group-camunda
        processChangeChannel-out-0:
          destination: topic-process-change
          content-type: application/json
          group: group-camunda

      rocketmq:
        binder:
          nameServer: namesrv:9876
        bindings:
          processChangeChannel-out-0:
            producer:
              group: group-camunda
              transactionListener: processStatusChangeTransactionListener
              producerType: Trans
              sendMessageTimeout: 60000




  jersey:
    applicationPath: /engine-rest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url.auth}/realms/house-sale
          jwk-set-uri: ${keycloak.url.token}/realms/house-sale/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${keycloak.client.id}
            client-secret: ${keycloak.client.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${keycloak.url.auth}/realms/house-sale
            authorization-uri: ${keycloak.url.auth}/realms/house-sale/protocol/openid-connect/auth
            user-info-uri: ${keycloak.url.auth}/realms/house-sale/protocol/openid-connect/userinfo
            token-uri: ${keycloak.url.token}/realms/house-sale/protocol/openid-connect/token
            jwk-set-uri: ${keycloak.url.token}/realms/house-sale/protocol/openid-connect/certs
            # set user-name-attribute one of:
            # - sub                -> default; using keycloak ID as camunda user ID
            # - email              -> useEmailAsCamundaUserId=true
            # - preferred_username -> useUsernameAsCamundaUserId=true
            user-name-attribute: preferred_username
  datasource:
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mariadb://192.168.1.21:3306/camunda?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullDatabaseMeansCurrent=true&nullCatalogMeansCurrent=true"
    username: "root"
    password: "5257mq"
    driver-class-name: "org.mariadb.jdbc.Driver"
#  jpa:
#    database: "MYSQL"
#    show-sql: "false"
#    hibernate:
#      naming:
#        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
#    properties:
#      hibernate:
#        ddl-auto: "none"
#        enable_lazy_load_no_trans: true
#        dialect: "org.hibernate.dialect.MySQL5Dialect"
